version: '3'

services:
    service-discovery-db:
        image: postgres:11.5
        volumes:
            - app-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: service-discovery-api
            POSTGRES_PASSWORD: secret-postgres-pass

    pgadmin:
        image: dpage/pgadmin4:4.12
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: dpage@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: dave-page

    service-discovery-api:
        build: .
        ports:
            - 8090:8090
        environment:
            APP_DB_HOST: service-discovery-db
            APP_DB_PORT: 5432
            APP_DB_USER: service-discovery-api
            APP_DB_PASS: secret-postgres-pass

volumes:
    app-db-data:
