server:
    port: 8090

spring:
    datasource:
        url: "jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/service-discovery-api"
        username: "${APP_DB_USER}"
        password: "${APP_DB_PASS}"

        hikari:
            initialization-fail-timeout: 10000

    jpa:
        show-sql: true

        hibernate:
            ddl-auto: validate

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    redis:
        host: ${APP_CACHE_HOST}

## Spring Data
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.show_sql=true